Repository Senac-SOR-ADS/Mapa-de-Sala, pull requests merged in 2024-09, with the labels that each got.

#8 Create readme.md
  documentação/readme.md
Labels: Doc

#10 Melhorada a classe de conexão
  model/conexao.py
Labels: Banco de Dados

#11 Adicionando o Banco de Dados
  bancoDeDados/Conceitual/projetoSenac.brM
  bancoDeDados/Físico/criação/teste.sql
  bancoDeDados/Físico/populado/testePopulado.sql
  bancoDeDados/Logíco/SCRIPTS/logicoScript.sql
  bancoDeDados/Logíco/logico.xml
  documentação/DBA/Conceitual/conceitual v4.png
  documentação/DBA/Lógico/logico v3.png
  model/teste.sql
Labels: Doc, Banco de Dados

#14 Criação interface login
  view/ui/imagem/logoSenac.png
  view/ui/interfaceLogin.ui
Labels: GUI

#15 Descrição das classes feitas.
  model/area.py
  model/curso.py
  model/equipamentos.py
  model/login.py
  model/pessoa.py
  model/reserva.py
  model/sala.py
Labels: Melhoria, Modelagem

#20 Alterações feitas no banco de dados para os equipamentos
  bancoDeDados/Conceitual/projetoSenac.brM
  bancoDeDados/Físico/criação/teste.sql
  bancoDeDados/Físico/populado/testePopulado.sql
  bancoDeDados/Logíco/SCRIPTS/logicoScript.sql
  bancoDeDados/Logíco/logico.xml
  documentação/DBA/Conceitual/conceitual v5.png
  documentação/DBA/Conceitual/conceitual v6.png
  documentação/DBA/Conceitual/conceitual v7.png
  documentação/DBA/Físico/fisico v2.png
  documentação/DBA/Físico/fisico v3.png
  documentação/DBA/Físico/fisico.png
  documentação/DBA/Lógico/logico v4.png
Labels: Melhoria, Banco de Dados

#23 Validação de Login + criação do .env de exemplo
  model/.env-exemplo
  model/conexao.py
  model/login.py
  model/pessoa.py
Labels: Melhoria

#27 Update Login
  view/home.py
  view/login.py
  view/minhaView.py
  view/ui/interfaceLogin.ui
Labels: Melhoria, GUI

#19 Interfaces transparente, feedbacks de resposta de dados, otimização de função
  view/login.py
  view/ui/interfaceLogin.ui
Labels: Melhoria, GUI

#29 Implementação de funções para criptografia e reservas
  model/criptografia.py
  model/reserva.py
Labels: Melhoria, Banco de Dados

#33 Funções da classe área
  model/area.py
Labels: Melhoria
