Repository Senac-SOR-ADS/Mapa-de-Sala, pull requests merged in 2024-11, with the labels that each got.

#98 Delete e Update na Area
  App/model/area.py
Labels: Banco de Dados

#99 Novas funções da model de curso
  App/model/curso.py
Labels: Melhoria, Modelagem

#100 Função no arquivo de conexão
  App/model/conexao.py
Labels: Melhoria

#103 Arrumando o sql populado
  Doc/bancoDeDados/Físico/populado/testePopulado.sql
Labels: Doc, Melhoria, Banco de Dados

#104 Adição do CRUD sala.py
  App/model/curso.py
  App/model/sala.py
Labels: Melhoria, Banco de Dados

#106 Ajuste no crud
  App/controller/pessoa.py
  App/model/login.py
  App/model/pessoa.py
Labels: Melhoria

#109 Arrumando StyleSheet e import
  App/view/login.py
  App/view/ui/home.ui
  App/view/ui/interfaceLogin.ui
Labels: Melhoria, GUI

#112 correção cadastro sala
  App/view/ui/cadastroSalas.ui
Labels: Melhoria, GUI

#114 Nova estrutura e arquivos do banco de dados
  Doc/bancoDeDados/Físico/oficial/criação/oficialt.sql
  Doc/bancoDeDados/Físico/oficial/populado/oficialt.sql
  Doc/bancoDeDados/Físico/teste/criação/teste.sql
  Doc/bancoDeDados/Físico/teste/populado/testePopulado.sql
Labels: Doc, Banco de Dados

#118 funções adicionada no CRUD (Update e Delete)
  App/controller/area.py
  App/controller/curso.py
  App/controller/reserva.py
  App/controller/sala.py
  App/controller/utils.py
  App/model/area.py
  App/model/reserva.py
  App/view/cadastrarArea.py
  App/view/cadastrarCurso.py
  App/view/cadastrarSalas.py
  App/view/cadastroPessoas.py
Labels: Melhoria, Banco de Dados

#126 Login nv e tema claro e escuro adicionados e home mlhr tmb
  App/view/cadastrarArea.py
  App/view/cadastrarCurso.py
  App/view/cadastrarLogin.py
  App/view/login.py
  App/view/ui/Login.ui
  App/view/ui/cadastroArea.ui
  App/view/ui/cadastroCurso.ui
  App/view/ui/cadastroLogin.ui
  App/view/ui/css/temaClaro/temaPrincipal.css
  App/view/ui/css/temaEscuro/temaPrincipal.css
  App/view/ui/home.ui
  App/view/ui/icones/crop_square_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png
  App/view/ui/icones/remove_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png
  App/view/ui/interfaceLogin.ui
  App/view/ui/menuQuebradoPessoas.ui
Labels: Melhoria, GUI

#130 Incrementando funcionalidade de Log na aplicação.
  App/controller/logger.py
  App/model/conexao.py
  App/view/home.py
  App/view/reserva.py
Labels: Melhoria

#140 Validação da Reserva
  App/controller/reserva.py
  App/model/reserva.py
  App/view/reserva.py
Labels: Melhoria, Banco de Dados

#142 Adicionando a validação no cadastro de curso
  App/controller/curso.py
  App/model/curso.py
  App/view/cadastrarCurso.py
Labels: Melhoria

#143 Ajustes nas telas de Cadastros
  App/view/cadastroPessoas.py
  App/view/ui/cadastroArea.ui
  App/view/ui/cadastroCurso.ui
  App/view/ui/cadastroLogin.ui
  App/view/ui/cadastroPessoas.ui
  App/view/ui/cadastroSalas.ui
  App/view/ui/editarArea.ui
  App/view/ui/editarCurso.ui
  App/view/ui/editarLogin.ui
  App/view/ui/editarPessoa.ui
  App/view/ui/editarReserva.ui
  App/view/ui/reserva.ui
Labels: Melhoria, GUI

#145 Data minima na reserva
  App/controller/area.py
  App/controller/curso.py
  App/controller/reserva.py
  App/view/reserva.py
Labels: Melhoria, Banco de Dados

#147 adicionando tela edit salas
  App/view/editarSala.py
  App/view/home.py
  App/view/ui/editarSalas.ui
  App/view/ui/home.ui
Labels: Melhoria, GUI
