Repository Senac-SOR-ADS/Mapa-de-Sala, pull requests merged in 2024-10, with the labels that each got.

#39 Implementado controlador para a Tela Principal
  controller/home.py
  controller/login.py
  controller/meuControlador.py
  main.py
  model/login.py
  view/login.py
Labels: GUI

#46 Alteração para QWidget nas telas de cadastros
  view/cadastrarArea.py
  view/cadastrarCurso.py
  view/cadastrarSalas.py
  view/cadastroPessoas.py
  view/ui/cadastroArea.ui
  view/ui/cadastroCurso.ui
  view/ui/cadastroPessoas.ui
Labels: Melhoria, GUI

#49 Atualizando a documentação do projeto
  bancoDeDados/Logíco/logico.xml
  documentação/DBA/Lógico/logico v5.png
Labels: Doc, Banco de Dados

#52 Alteração na tela de cadastros
  view/cadastrarCurso.py
  view/cadastrarSalas.py
  view/ui/cadastroCurso.ui
  view/ui/cadastroSalas.ui
Labels: Melhoria, GUI

#53 Alteração nas telas
  view/cadastrarArea.py
  view/cadastrarCurso.py
  view/cadastrarSalas.py
  view/cadastroPessoas.py
  view/reserva.py
  view/ui/cadastroCurso.ui
Labels: Melhoria, GUI

#55 Controller da sala
  controller/sala.py
  main.py
  model/sala.py
Labels: GUI

#59 trocado o caminho das interfaces para adaptar para nova estrutura
  App/view/cadastrarArea.py
  App/view/cadastrarCurso.py
  App/view/cadastrarSalas.py
  App/view/cadastroPessoas.py
  App/view/home.py
  App/view/login.py
  App/view/reserva.py
Labels: Melhoria, GUI

#61 Nova estrutura para o cadastro de salas
  App/controller/sala.py
  App/view/cadastrarSalas.py
Labels: Melhoria

#62 novo controller Area
  App/controller/area.py
  App/view/cadastrarArea.py
Labels: Melhoria

#64 Controle de cadastrar Pessoa.
  App/controller/pessoa.py
  App/model/pessoa.py
  App/view/cadastroPessoas.py
Labels: Melhoria

#66 Deixando o código mais simples
  App/controller/sala.py
  App/view/cadastrarSalas.py
Labels: Melhoria

#68 Alteração interface Reserva
  App/view/ui/reserva.ui
Labels: Melhoria, GUI

#69 Modulo web
  App/__init__.py
  App/routes/__init__.py
  App/routes/acesso.py
  App/routes/routes.py
  App/static/js/script.js
  App/templates/base.html
  App/templates/error404.html
  App/templates/home.html
  App/templates/login.html
  App/templates/logout.html
  App/web.py
  main.py
Labels: GUI

#73 Connect buttons - Alterações (Home, Login)
  App/view/home.py
  App/view/login.py
  App/view/ui/interfaceLogin.ui
Labels: Melhoria, GUI

#75 Novos modelos do banco
  Doc/bancoDeDados/Conceitual/projetoSenac.brM
  Doc/bancoDeDados/Físico/criação/teste.sql
  Doc/bancoDeDados/Físico/populado/testePopulado.sql
  Doc/bancoDeDados/Logíco/SCRIPTS/logicoScript.sql
  Doc/bancoDeDados/Logíco/logico.xml
  Doc/documentação/DBA/Conceitual/conceitual v8.png
  Doc/documentação/DBA/Físico/fisico v4.png
  Doc/documentação/DBA/Lógico/logico v6.png
Labels: Melhoria, Banco de Dados

#77 Alteração dos import
  App/view/home.py
Labels: Melhoria, GUI

#78 Alteração Reserva
  App/view/reserva.py
  App/view/ui/reserva.ui
Labels: Melhoria, GUI

#81 Modificando a tela de reservas
  App/view/cadastrarLogin.py
  App/view/reserva.py
Labels: Melhoria, GUI

#83 Arrrumando o sql do banco
  Doc/bancoDeDados/Físico/criação/teste.sql
  Doc/bancoDeDados/Físico/populado/testePopulado.sql
Labels: Banco de Dados

#85 Arrumando campo do cargo
  Doc/bancoDeDados/Físico/criação/teste.sql
  Doc/bancoDeDados/Físico/populado/testePopulado.sql
Labels: Banco de Dados

#92 Mudar tema
  App/view/configurarTela.py
  App/view/home.py
  App/view/ui/css/temaClaro/temaPrincipal.css
  App/view/ui/css/temaEscuro/temaPrincipal.css
  App/view/ui/icones/toggleOff.png
  App/view/ui/icones/toggleOn.png
  App/view/ui/telaConfiguracoes.ui
Labels: Melhoria, GUI

#93 Controller Reserva concluída
  App/controller/pessoa.py
  App/controller/reserva.py
  App/model/conexao.py
  App/model/reserva.py
  App/view/cadastroPessoas.py
  App/view/reserva.py
  Doc/bancoDeDados/Físico/populado/testePopulado.sql
Labels: Melhoria

#95 Modificação do conector do banco de dados
  App/desktop.py
  App/model/conexao.py
Labels: Banco de Dados
