Repository Senac-SOR-ADS/Mapa-de-Sala, pull requests merged in 2024-12, with the labels that each got.

#150 Mudança de erro de ortografia
  App/view/ui/cadastroLogin.ui
Labels: Melhoria, help wanted, GUI

#152 Verificação do dia da semana
  App/controller/reserva.py
  App/view/reserva.py
Labels: Melhoria

#153 colocando as telas de concuido e erro
  App/view/feadbackConcluido.py
  App/view/feadbackErro.py
  App/view/login.py
  App/view/ui/Login.ui
  App/view/ui/cadastroArea.ui
  App/view/ui/cadastroCurso.ui
  App/view/ui/cadastroErro.ui
  App/view/ui/cadastroLogin.ui
  App/view/ui/cadastroPessoas.ui
  App/view/ui/feadbackConcluido.ui
  App/view/ui/feadbackErro.ui
  App/view/ui/home.ui
  App/view/ui/icones/iconRelatorioBranco.png
Labels: Melhoria, GUI

#154 Ajustando os retornos do código
  App/controller/reserva.py
  App/view/reserva.py
Labels: Melhoria

#155 Horario minimo
  App/view/reserva.py
Labels: Melhoria

#157 Editar Area
  App/view/cadastrarArea.py
  App/view/editarArea.py
Labels: Banco de Dados

#158 Modificação nas telas de Editar e Cadastro
  App/view/ui/cadastroArea.ui
  App/view/ui/cadastroCurso.ui
  App/view/ui/cadastroPessoas.ui
  App/view/ui/cadastroSalas.ui
  App/view/ui/editarArea.ui
  App/view/ui/editarCurso.ui
  App/view/ui/editarLogin.ui
  App/view/ui/editarPessoa.ui
  App/view/ui/editarReserva.ui
  App/view/ui/editarSalas.ui
  App/view/ui/home.ui
  App/view/ui/reserva.ui
Labels: Melhoria, GUI

#159 editarLogin alterado
  App/view/ui/editarLogin.ui
Labels: Melhoria, GUI

#162 Inserção do modo de autenticação
  App/controller/login.py
Labels: Melhoria, CRÍTICO

#163 Tela de editar curso alterado
  App/view/ui/editarCurso.ui
Labels: Melhoria, GUI

#168 Tela de EditarCurso e Cadastro Salas
  App/view/ui/cadastroSalas.ui
  App/view/ui/editarArea.ui
  App/view/ui/editarCurso.ui
Labels: Melhoria, GUI

#170 Função de Editar Sala
  App/controller/sala.py
  App/model/sala.py
  App/view/editarSala.py
Labels: Banco de Dados

#174 Reserva alterada
  App/view/ui/reserva.ui
Labels: Melhoria, GUI

#175 Período na reserva
  App/controller/curso.py
  App/model/curso.py
  App/view/editarLogin.py
  App/view/reserva.py
Labels: Melhoria, Banco de Dados
