Repository Senac-SOR-ADS/Mapa-de-Sala, pull requests merged in 2025-02, with the labels that each got.

#210 Arrumando Responsividade
  App/view/cadastrarCurso.py
  App/view/editarSala.py
  App/view/ui/Login.ui
  App/view/ui/cadastroArea.ui
  App/view/ui/cadastroCurso.ui
  App/view/ui/cadastroLogin.ui
  App/view/ui/cadastroPessoas.ui
  App/view/ui/cadastroSalas.ui
  App/view/ui/editarArea.ui
  App/view/ui/editarCurso.ui
  App/view/ui/editarLogin.ui
  App/view/ui/editarPessoa.ui
  App/view/ui/editarSalas.ui
  App/view/ui/home.ui
Labels: Melhoria, GUI

#216 Listagem de sala
  App/model/sala.py
Labels: Melhoria, Banco de Dados, Modelagem

#217 Código base para a edição de reservas
  App/model/reserva.py
  App/view/editarReserva.py
Labels: Melhoria, Banco de Dados

#211 Tela pesquisa
  App/view/feedback.py
  App/view/home.py
  App/view/login.py
  App/view/pesquisa.py
  App/view/ui/home.ui
  App/view/ui/icones/iconEditPen.png
  App/view/ui/icones/iconLixeira.png
  App/view/ui/pesquisa.ui
Labels: GUI

#219 Tela confirmacao resolucao
  App/view/feedback.py
  App/view/home.py
  App/view/login.py
  App/view/telaConfirmacao.py
  App/view/ui/css/temaEscuro/temaPrincipal.css
  App/view/ui/feedback.ui
  App/view/ui/home.ui
  App/view/ui/icones/iconNotificacao.png
  App/view/ui/icones/iconTeste.png
  App/view/ui/telaConfirmacao.ui
Labels: GUI

#220 Correções na função de editar sala
  App/controller/sala.py
  App/model/sala.py
  App/view/editarSala.py
Labels: Melhoria, Banco de Dados

#222 desabilitando edição do campo de area da tela de editar curso
  App/view/ui/editarCurso.ui
Labels: GUI

#223 Alteração no curso
  App/view/cadastrarCurso.py
  App/view/ui/cadastroCurso.ui
Labels: Melhoria, GUI

#224 Tela de pesquisa
  App/view/pesquisa.py
  App/view/ui/pesquisa.ui
Labels: Melhoria

#228 tela pesquisa feita com um card de exemplo ja
  App/view/pesquisa.py
  App/view/telaConfirmacao.py
  App/view/ui/icones/iconManha.png
  App/view/ui/icones/iconTarde.png
  App/view/ui/pesquisa.ui
Labels: GUI

#229 Atualizando SQL
  Doc/bancoDeDados/Físico/oficial/criação/oficialt.sql
  Doc/bancoDeDados/Físico/oficial/populado/oficialt.sql
  Doc/bancoDeDados/Físico/teste/criação/teste.sql
  Doc/bancoDeDados/Físico/teste/populado/testePopulado.sql
Labels: Banco de Dados

#233 Nova tela de Reserva
  App/view/reserva.py
  App/view/ui/icones/iconCheckAtivo.png
  App/view/ui/icones/iconCheckLaranja.png
  App/view/ui/reserva.ui
Labels: Melhoria, GUI

#236 Tela de pesquisa
  App/controller/reserva.py
  App/view/pesquisa.py
Labels: Melhoria

#237 Retornando objetos
  App/model/reserva.py
Labels: Banco de Dados

#238 Listando reserva
  App/model/reserva.py
Labels: Banco de Dados

#235 pesquisa de reserva múltipla
  App/view/ui/cardPesquisa.ui
  App/view/ui/css/cards/manha.css
  App/view/ui/css/cards/noite.css
  App/view/ui/css/cards/tarde.css
  App/view/ui/pesquisa.ui
Labels: GUI

#240 População da tela reserva múltipla
  App/view/pesquisa.py
Labels: Melhoria, Banco de Dados

#244 Model Reserva
  App/model/reserva.py
Labels: Melhoria, Banco de Dados

#250 Tela conflitos
  App/view/feedback.py
  App/view/home.py
  App/view/reserva.py
  App/view/telaConfirmacao.py
  App/view/telaConflitos.py
  App/view/ui/telaConfirmacao.ui
  App/view/ui/telaConflitos.ui
Labels: GUI

#253 Novas queries
  Doc/bancoDeDados/Físico/oficial/criação/oficialt.sql
  Doc/bancoDeDados/Físico/oficial/populado/oficialt.sql
  Doc/bancoDeDados/Físico/teste/criação/teste.sql
  Doc/bancoDeDados/Físico/teste/populado/testePopulado.sql
Labels: Banco de Dados
