Repository Senac-SOR-ADS/Mapa-de-Sala, pull requests merged in 2025-03, with the labels that each got.

#255 Criando nova Tela de Confirmação
  App/view/ui/icones/iconAjuda.png
  App/view/ui/telaConfirmacao.ui
  App/view/ui/telaConflitos.ui
Labels: Melhoria, GUI

#254 Validações e confirmações
  App/controller/pessoa.py
  App/controller/sala.py
  App/controller/utils.py
  App/model/curso.py
  App/model/login.py
  App/view/cadastrarArea.py
  App/view/cadastrarCurso.py
  App/view/cadastrarSalas.py
  App/view/cadastroPessoas.py
  App/view/editarArea.py
  App/view/editarCurso.py
  App/view/editarLogin.py
  App/view/editarPessoas.py
  App/view/editarSala.py
  App/view/reserva.py
Labels: Melhoria, Banco de Dados

#256 Arrumando horário do curso
  App/view/editarCurso.py
Labels: Melhoria

#258 Css dos cards
  App/view/ui/cardPesquisa.ui
  App/view/ui/css/cards/manha.css
  App/view/ui/css/cards/noite.css
  App/view/ui/css/cards/tarde.css
  App/view/ui/icones/iconEditarPreto.png
  App/view/ui/icones/iconLixeiraPreto.png
Labels: GUI

#259 Adicionando nova tela de feedback
  App/view/feedback.py
  App/view/login.py
  App/view/ui/feedback.ui
  App/view/ui/icones/iconErro2.png
Labels: Melhoria, GUI

#261 Módulo WEB e Desktop (MODEL)
  App/controller/logger.py
  App/model/area.py
  App/model/conexao.py
  App/model/criptografia.py
  App/model/curso.py
  App/model/equipamentos.py
  App/model/logger.py
  App/model/login.py
  App/model/pessoa.py
  App/model/reserva.py
  App/model/sala.py
Labels: Melhoria

#265 Melhoria no Editar Login
  App/view/ui/editarLogin.ui
Labels: Melhoria, GUI

#271 Função de cursos finalizando
  App/model/relatorio.py
Labels: Banco de Dados

#273 Consultar relatorio
  App/view/consultarReserva.py
  App/view/home.py
  App/view/ui/consultarReserva.ui
  App/view/ui/home.ui
Labels: Melhoria, GUI
